// <auto-generated />
namespace CRM_v2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CtrlActStatCreateContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CtrlActStatCreateContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201407081513565_CtrlActStatCreateContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
